audio:
  sampleRate: 48000
  channels: 2
  frameSize: 20
  defaultBitrate: 128
  jitterBufferMs: 40
  device:
    inputDeviceId: Loopback Audio 4
    outputDeviceId: Périphérique agrégé
    sampleRate: 48000
  channelNames:
    inputs:
      "0": Loopback L
      "1": Loopback R
    outputs:
      "0": Casque L
      "1": Casque R
      "2": Mac L
      "3": Mac R
server_audio_users:
  - name: Utilisateur Serveur
    group: default
    input_channel: 0
    output_channel: 0
groups:
  - name: Default
    audioBitrate: 96
    channels: []
  - name: Production
    audioBitrate: 96
    channels: []
  - name: Technique
    audioBitrate: 96
    channels: []
server:
  host: 0.0.0.0
  port: 3000
  livekit:
    url: AUTO
logging:
  level: debug
  logLatency: false
  logAudioStats: false
