inputs:
  Microphone MacBook Pro:
    channels: 1
    names:
      "0": Loopback L
      "1": Loopback R
outputs:
  Haut-parleurs MacBook Pro:
    channels: 4
    names:
      "0": Casque L
      "1": Casque R
      "2": Mac L
      "3": Mac R
